server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ud4rkSDimkaA/Innowise-Internship-Microservices
          clone-on-start: true
          search-paths: configs